#!/bin/bash
# --------------------------------------------------
# Request resources here
# --------------------------------------------------
#BSUB -J 01C_run_fastqc-lsf[1-15]%15       # job name, with array number to run in parallel
#BSUB -n 2                                 # number of CPUs required per task
#BSUB -q shared_memory                     # the queue to run on
#BSUB -R "span[hosts=1]"                   # number of hosts to spread the jobs across, 1 host used here
#BSUB -R "rusage[mem=4GB]"                 # required total memory for the job 
#BSUB -o "./output.%J_%I.log"              # standard output file (%J is job name, %I is the array number)
#BSUB -e "./error.%J_%I.log"               # standard error file (%J is job ID, %I is the array number)
#BSUB -W 10:00                             # time to run

# --------------------------------------------------
# Load modules here
# --------------------------------------------------

# --------------------------------------------------
# Execute commands here
# --------------------------------------------------

# echo for log
echo "job started"; pwd; hostname; date

# source config gile and get sample name from input list based on job array index
source ./config.sh
export SAMPLE=`head -n +${LSB_JOBINDEX} $IN_LIST | tail -n 1`

# run FastQC
echo "Running FastQC on sample $SAMPLE" 
apptainer run ${FASTQC} fastqc ${WORK_DIR}/trimmed_reads/${SAMPLE}_*.fastq*

# move FastQC results to a separate directory and copy to local directory for viewing
# create directory if it does not exist
TRIM_DIR="${WORK_DIR}/after_qc_trimming"
if [[ ! -d "$TRIM_DIR" ]]; then
  echo "$TRIM_DIR does not exist. Directory created"
  mkdir -p $TRIM_DIR
fi
#  move files
mv ${WORK_DIR}/trimmed_reads/${SAMPLE}_*_fastqc.html $TRIM_DIR
mv ${WORK_DIR}/trimmed_reads/${SAMPLE}_*_fastqc.zip $TRIM_DIR
cp -r $TRIM_DIR ~/01_qc_trimming

# print date for log
echo "job ended"; date

